### ISSUE TITLE
Typings needs update

### ISSUE THREAD

**Issue by CraigWarford** [danwild/generator-angular-typescript-gulp#1]
With 1.0 of Typings, the file is no longer main.d.ts, it is index.d.ts, so the references need updating.  Also, "typings install" is not updating the references for angular or ng namespaces, so errors are generated during compile.  (Running "typings install" indicates there are no dependencies.)

**Comment by Zimmergren** [comment]
I just ran this for some scaffolding today for some test projects, and it looks like the issue remains. Any updates on whether the generator will be updated?
Changing this to `index.d.ts` works as suggested by CraigWarford, but alas, would be neat to avoid that extra step.

**Comment by johnazre** [comment]
In the typings.json file, if you change "ambientDependencies" to "globalDependencies", as well as changed "main.d.ts" to "index.d.ts", that worked for me.

**Comment by johnazre** [comment]
PRs submitted.

**Comment by danwild** [comment]
Thanks, PR's #2, #3, #4 and #5 have been merged and npm published with changes in version 1.0.1
